### PR TITLE
add theming

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by stan-dot** [comment]
necessary for this
https://github.com/bluesky/ophyd-async/issues/268

**Comment by garryod** [comment]
> necessary for this [bluesky/ophyd-async#268](https://github.com/bluesky/ophyd-async/issues/268)

Any chance you could explain what this config does and why it helps with the issue you've linked? I'm not quite sure I follow

**Comment by stan-dot** [comment]
`
!!! tip inline end "Choose the right interfaces@

  If it's your first time writing `ophyd_async devices`, [this flowchart](https://blueskyproject.io/ophyd-async/main/how-to/choose-interfaces-for-devices.html) can be useful in helping you choose which interfaces does a device need.

`
you asked about that this is a good use case for adomitions, and this text here uses the 'tip' admonition, so I add the icon. 

admonitions docs had this whole array of other icons too and keyboard shortcuts so I included them along

**Comment by garryod** [comment]
> ```markdown
> !!! tip inline end "Choose the right interfaces@
> 
> If it's your first time writing `ophyd_async devices`, [this flowchart](https://blueskyproject.io/ophyd-async/main/how-to/choose-interfaces-for-devices.html) can be useful in helping you choose which interfaces does a device need.
> 
> ```
> you asked about that this is a good use case for adomitions, and this text here uses the 'tip' admonition, so I add the icon.
> 
> admonitions docs had this whole array of other icons too and keyboard shortcuts so I included them along

Admonitions are already part of the configuration, and the icons are specified by default, are you changing the defaults for some reason? Also, not sure how keyboard shortcuts are relevant here, though they're nice to have so would be happy for them to be added in a separate PR. What's going on with the syntax highlighting config?

**Comment by stan-dot** [comment]
my bad, I overlooked that there are defaults provided

**Pull request closed without merging**
